[package]
name = "wanderlot"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.42.0" }

[addresses]
wanderlot = "0x0"
